Services - Warehouse Services:
  summary: Warehouse Services
  description: >-
    This elaborates the model implementations for booking warehouse services over the network.
    The booking majorly happens in four phases of order processing flow, i.e. Discovery of available services and service providers based on serviceability, order, fulfillment and post-fulfillment.
  example_set:
    $ref: "./Warehouse_services_yaml/index.yaml"
